#!/bin/bash
#查找某日期距离今天的天数(可前也可后)
#用零时时间戳计算，不用考虑小数问题

### Description:
###     Daysago — calculate the days between a date and today.
###
### Date: 2020.07.09
### Author: Shieber
### Email: QMH_XB_FLTMY@yahoo.com
###
### Usage:
###     Daysago <date>
###
### Options:
###     <date>     Input a date.
###     -h,--help   Show help message.
###
### Example:
###     Daysago 2020-01-01
###     Daysago 2020-12-31
help() {
    sed -rn 's/^### ?//;T;p' "$0"
}

secondPerday=86400

if [[ $# == 0 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
    exit 1
else                                                #有参数，转换为对应时间戳
    timeStampInput=`date -d $1 +%s`                 #输入日期零时时间戳
    Today=`date +%Y-%m-%d`                          #今日日期
    timeStampToday=`date -d $Today +%s`             #今日零时时间戳

    if [ $timeStampToday -ge $timeStampInput ]; then  #以前时间
        days=$[ ($timeStampToday - $timeStampInput) / $secondPerday ] #计算天数
        if [ $days -gt 1 ]; then
            days="$days days ago"                 
        else
            days="$days day ago"                 
        fi
    else                                              #未来时间(含今天)
        days=$[ ($timeStampInput - $timeStampToday) / $secondPerday ] #计算天数
        if [ $days -gt 1 ]; then
            days="$days days after"
        else
            days="$days day after"
        fi
    fi

    echo $days
fi
