#!/bin/bash
#用eog查看图片

if [ ! -n "$1" ] #无参数，显示用法
    then
        echo "Usage: ${0##*/} picture.[png|jpeg|jpg]"
else             #有参数，判断输入参数格式是否为图片并打开
    if [ ${1##*.} = "png" ]
        then
            eog $1 >/dev/null 2>&1 &
    elif [ ${1##*.} = "jpg" ]
        then
            eog $1 >/dev/null 2>&1 &
    elif [ ${1##*.} = "jpeg" ]
        then
            eog $1 >/dev/null 2>&1 &
    elif [ ${1##*.} = "gif" ]
        then
            eog $1 >/dev/null 2>&1 &
    else
        echo 'Wrong format, file must end with [png, jpg, jgep, gif]'
    fi
fi
