#!/bin/bash
#转换xhtml html htm文件为txt

function dump2txt(){
    if   [ ${1##*.} = "html"  ]; then
        lynx -dump ${1} > ${1%.*}.txt 2>/dev/null  
    elif [ ${1##*.} = "xhtml" ]; then 
        lynx -dump ${1} > ${1%.*}.txt 2>/dev/null  
    elif [ ${1##*.} = "htm"   ]; then 
        lynx -dump ${1} > ${1%.*}.txt 2>/dev/null  
    fi
}

if [ -n "${1}" ]; then #有输入参数，依后缀转换(x)html文件
    dump2txt ${1}
else                   #无输入参数，转换当前目录下所有(x)html文件
    for file in `ls .`
    do
        dump2txt ${file}
    done
fi
