#!/bin/bash
#set -euxo pipefail
#安全删除文件，将rm给管起来，误删可恢复
#需要在某处创建一个垃圾箱目录如/home/username/Trash

#判断目录是否存在，不存在则创建
USERNAME=`logname`
TRASH_DIR="/home/$USERNAME/Trash"
if [ ! -d "$TRASH_DIR" ]; then
    mkdir -p "$TRASH_DIR"
    echo "删除文件存放在$TRASH_DIR"
    echo "建议将如下内容加入/etc/crontab"
    echo "每晚8点自动清理$TRASH_DIR下内容"
    echo "0  20	* * *	root	/bin/rm -rf $TRASH_DIR/*"
fi

#给文件添加时间戳并移动到TRASH_DIR
for file in $*; do
	STAMP=`date +%s`
	FILENAME=`basename $file`
	mv $file $TRASH_DIR/$FILENAME.$STAMP
done
