#!/bin/bash
#查看系统信息，需要输入root密码作为参数

### Description:
###     SystemInfo — show system information
###
### Date: 2020.07.09
### Author: Shieber
### Email: QMH_XB_FLTMY@yahoo.com
###
### Usage:
###     SystemInfo  <passwd>
###
### Options:
###     <passwd>     Input your sudo password.
###     -h,--help   Show help message.
###
### Support Info: 
###     PC brand, Memory, CPU, Kernel, OS, Hardware 
###
### Example:
###     SystemInfo my-password
help() {
    sed -rn 's/^### ?//;T;p' "$0"
}

function systemInfo() {
    echo "1. equipment brand: `echo ${1}|sudo -S dmidecode -s system-product-name`"
    echo "2. OS info: `echo ${1}|sudo -S lsb_release -d | grep "Description"|awk -F: '{print $2}'`"
    echo "3. kernel info: `uname -s -m -r`"
    echo "4. hardware platform: `uname -i`"
    echo "5. cpu info:"
    echo "        brand and freq: `cat /proc/cpuinfo |grep "model name"|uniq |awk -F: '{print $2}'`"
    echo "        physical CPUs:`cat /proc/cpuinfo |grep "physical id"|sort |uniq|wc -l`"
    echo "        physical cores per CPU: `cat /proc/cpuinfo |grep "cpu cores"|uniq|awk -F: '{print $2}'`"
    echo "        logical cores per CPU: `cat /proc/cpuinfo |grep "siblings"|uniq|awk -F: '{print $2}'`"
    echo "        total logic cores: `cat /proc/cpuinfo |grep -c "processor"`"
    echo "6. memory slots and size: `echo ${1}|sudo -S dmidecode|grep -P -A5 "Memory Device" |grep Size | uniq`"
    echo "7. maximum capacity of memory: `echo ${1}|sudo -S dmidecode -t memory |grep "Maximum Capacity"| awk -F: '{print $2}'`"
    echo "8. memory `echo ${1}|sudo -S dmidecode|grep -A16 "Memory Device"|grep 'Speed' | uniq`"
}

if [[ $# == 0 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
    exit 1
else
    systemInfo $1
fi
