#!/bin/bash
# 合并两个mp4视频文件为一个

if [ $# -ne 3 ]
    then
        echo "Usage: ${0##*/} input1.mp4 input2.mp4 output.mp4"
else
    for file in $*
    do 
        if [ "${file##*.}" != "mp4" ]
        then
            echo "Usage: ${0##*/} input1.mp4 input2.mp4 output.mp4"
            exit 1
        fi
    done
    mencoder -ovc copy -oac mp3lame $1 $2 -o $3
fi
