#!/bin/bash
#set -euxo pipefail
# 从视频文件中提取出音频

function convert2radio() {
    if   [ ${1##*.} = "mp4"  ]; then
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "flv"  ]; then
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "avi"  ]; then
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "mkv"  ]; then 
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "mpg"  ]; then 
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "mpeg" ]; then 
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "rmvb" ]; then 
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    elif [ ${1##*.} = "wmv"  ]; then 
        ffmpeg -i ${1} -f mp3 -vn ${1%.*}.mp3 2>/dev/null
    fi
}


if [ -n "${1}" ]; then #有参数，直接提取
    convert2radio ${1}
else                   #无参数，提取当前目录所有
    for video in `ls .`
    do 
        convert2radio ${video}
    done
fi
