#!/bin/bash
# 2020-06-21
# 用you-get下载神器下载视频，

# sudo pip3 install you-get
# 1.可以直接输入url下载视频文件，
# 2.可以按url逐个下载视频文件，把url放到某文件里，
#   一行一个视频url地址，具体格式如video.url

if [ ! -n "${1}" ]; then  #无参数，显示用法
    echo "Usage1: ${0##*/} https://www.youtube.com/xxxx"
    echo "Usage2: ${0##*/} xxx.url"
elif [ -f "${1}" ]; then  #参数为url文件，逐个下载 
    while read url
    do
        you-get ${url}
    done < ${1}
else                      #参数为url，直接下载
    you-get ${1}
fi
