#!/bin/bash
# Date: 2020.07.09
# 查看电池信息

### Description:
###     Battery  — show battery information.
###
### Author: 
###     Shieber https://github.com/QMHTMY
###
### Usage:
###     Battery [Options]
###
### Options:
###     -h,--help   Display help message.
###
### Example:
###     Battery 
###     Battery -h
###     Battery --help
help() {
    sed -rn 's/^### ?//;T;p' "$0"
}


if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
    exit 1
else
    upower -i `upower -e | grep 'BAT'`
fi
