#!/bin/bash
# Date: 2020.07.14
# 用opencc进行简繁转换
# sudo apt install opencc

### Description:
###     Simple2t — convert Simplified Chinese to Traditional Chinese.
###
### Author: 
###     Shieber https://github.com/QMHTMY
###
### Depnedency:
###     sudo apt install opencc
###
### Usage:
###     Simple2t <s-chars>         
###     Simple2t <ifile>           
###     Simple2t <ifile> <ofile>   
###
### Options:
###     <s-chars>   Input Simplified Chinese characters.
###     <ifile>     Input a filename which contains Simplified Chinese characters.
###     <ofile>     Input a filename for saving the output.
###     -h,--help   Display help message.
###
### Example:
###     Simple2t 庆丰
###     Simple2t siplified.txt
###     Simple2t siplified.txt traditional.txt
help() {
    sed -rn 's/^### ?//;T;p' "$0"
}


if [[ $# == 0 ]] || [[ $# > 2 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
    exit 1
elif [[ $# == 1 ]]; then             #只有一个参数   
    if [[ -f $1 ]]; then             #若是文件，转换后输出到标准输出
        opencc -c s2t -i $1                                                            
    else                             #若是字符，转换后输出到标准输出
        echo $1 | opencc -c s2t                                                        
    fi                                                                                 
else                                 #有两个参数
    if [[ -f $1 ]]; then             #第一个参数为文件，转换后输出到第二个参数对应文件
        opencc -c s2t -i $1 -o $2                                                      
    else                             #第一个参数非文件，则报错                        
        help
    fi
fi
