#!/bin/bash
#查看系统文件大小统计信息，需要输入 root 密码

### Description:
###     SystemFileInfo — show system files statistics information
###
### Date: 2021.04.21
### Author: Shieber
### Email: QMH_XB_FLTMY@yahoo.com
###
### Usage:
###     SystemFileInfo  <passwd>
###
### Options:
###     <passwd>    Input your sudo password.
###     -h,--help   Show help message.
###
### Example:
###     SystemFileInfo my-password
help() {
    sed -rn 's/^### ?//;T;p' "$0"
}

function static() {
    echo ${1} | sudo -S find $HOME -type f -printf "%s %p\n" > home_files_stats.txt
    SystemFileStatic home_files_stats.txt
    rm home_files_stats.txt
}

if [[ $# == 0 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
    exit 1
else
    static $1
fi
